package <%=packageName%>.test.business.business

import <%=packageName%>.business.I<%=entityClass%>Business
import <%=packageName%>.business.impl.<%=entityClass%>Business
import <%=packageName%>.domain.search.<%=entityClass%>
import <%=packageName%>.repository.search.I<%=entityClass%>SearchRepository
import org.springframework.data.domain.PageImpl
import org.springframework.data.domain.PageRequest
import spock.lang.Specification

/**
 * Generated unit test for the <%=entityClass%>Business objects.
 */
class <%=entityClass%>BusinessUnitSpec extends Specification {

    I<%=entityClass%>Business <%=entityInstance%>Business;

    def setup() {
        this.<%=entityInstance%>Business = new <%=entityClass%>Business();
    }

    def "simple findOne method spec generated by the framework"() {

        setup:
        def <%=entityInstance%>SearchRepository = Mock(I<%=entityClass%>SearchRepository);
        this.<%=entityInstance%>Business.<%=entityInstance%>Repository = <%=entityInstance%>SearchRepository;
        def r<%=entityInstance%> = [id:"1"] as <%=entityClass%>;

        when:
        def <%=entityInstance%> = this.<%=entityInstance%>Business.findOne("1");

        then:
        1 * <%=entityInstance%>SearchRepository.findOne(_) >> r<%=entityInstance%>;
        <%=entityInstance%> != null;
        <%=entityInstance%>.id == "1";
    }

    def "simple find all method spec generated by the framework"() {

        setup:
        def <%=entityInstance%>SearchRepository = Mock(I<%=entityClass%>SearchRepository);
        this.<%=entityInstance%>Business.<%=entityInstance%>Repository = <%=entityInstance%>SearchRepository;
        def r<%=entityInstance%>s = [[id:"1"] as <%=entityClass%>, [id:"1"] as <%=entityClass%>];

        when:
        def <%=entityInstance%>s = this.<%=entityInstance%>Business.findAll(new PageRequest(1, 1));

        then:
        1 * <%=entityInstance%>SearchRepository.findAll(_) >> new PageImpl<<%=entityClass%>>(r<%=entityInstance%>s);
        <%=entityInstance%>s.getTotalElements() == 2;
    }

    def "simple save method generated by the framework"(){

        setup:
        def <%=entityInstance%>SearchRepository = Mock(I<%=entityClass%>SearchRepository);
        this.<%=entityInstance%>Business.<%=entityInstance%>Repository = <%=entityInstance%>SearchRepository;
        def r<%=entityInstance%> = [id:"1"] as <%=entityClass%>;

        when:
        def saved<%=entityClass%> = this.<%=entityInstance%>Business.save([]as <%=entityClass%>);

        then:
        1 * <%=entityInstance%>SearchRepository.save(_) >> r<%=entityInstance%>;
        saved<%=entityClass%>.id != null;
    }

    def "simple delete method generated by the framework"() {
        setup:
        def <%=entityInstance%>SearchRepository = Mock(I<%=entityClass%>SearchRepository);
        this.<%=entityInstance%>Business.<%=entityInstance%>Repository = <%=entityInstance%>SearchRepository;

        when:
        this.<%=entityInstance%>Business.delete([] as <%=entityClass%>);

        then:
        1 * <%=entityInstance%>SearchRepository.delete(_);
    }
}
