management.security.enabled: false
security.basic.enabled: false

server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: <%= baseName %>
